name: 'Yoast plugin mirror automation'
description: 'Automate Yoast plugin mirroring on GitHub.'
author: 'codewurker'

branding:
  icon: 'upload-cloud'
  color: 'orange'

inputs:
  yoast-url:
    description: >
      Yoast URL.
    required: true
  yoast-product-slug:
    description: >
      Yoast product slug.
    required: true

runs:
  using: 'composite'
  steps:
    - id: mirror
      run: php ${{ github.action_path }}/mirror.php
      shell: bash
      env:
        INPUT_YOAST-URL: ${{ inputs.yoast-url }}
        INPUT_YOAST-PRODUCT-SLUG: ${{ inputs.yoast-product-slug }}
